// Code generated by protoc-gen-go.
// source: bazil.org/bazil/db/wire/volume.proto
// DO NOT EDIT!

/*
Package wire is a generated protocol buffer package.

It is generated from these files:
	bazil.org/bazil/db/wire/volume.proto

It has these top-level messages:
	VolumeStorage
*/
package wire

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type VolumeStorage struct {
	Backend        string `protobuf:"bytes,1,opt,name=backend" json:"backend,omitempty"`
	SharingKeyName string `protobuf:"bytes,2,opt,name=sharingKeyName" json:"sharingKeyName,omitempty"`
}

func (m *VolumeStorage) Reset()         { *m = VolumeStorage{} }
func (m *VolumeStorage) String() string { return proto.CompactTextString(m) }
func (*VolumeStorage) ProtoMessage()    {}
