// Code generated by protoc-gen-go.
// source: bazil.org/bazil/control/wire/peer.proto
// DO NOT EDIT!

package wire

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type PeerAddRequest struct {
	// Must be exactly 32 bytes long.
	Pub []byte `protobuf:"bytes,2,opt,name=pub,proto3" json:"pub,omitempty"`
}

func (m *PeerAddRequest) Reset()         { *m = PeerAddRequest{} }
func (m *PeerAddRequest) String() string { return proto.CompactTextString(m) }
func (*PeerAddRequest) ProtoMessage()    {}

type PeerAddResponse struct {
}

func (m *PeerAddResponse) Reset()         { *m = PeerAddResponse{} }
func (m *PeerAddResponse) String() string { return proto.CompactTextString(m) }
func (*PeerAddResponse) ProtoMessage()    {}

func init() {
}
