// Code generated by protoc-gen-go.
// source: bazil.org/bazil/control/wire/volume.proto
// DO NOT EDIT!

/*
Package wire is a generated protocol buffer package.

It is generated from these files:
	bazil.org/bazil/control/wire/volume.proto

It has these top-level messages:
	VolumeMountRequest
	VolumeCreateRequest
*/
package wire

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type VolumeMountRequest struct {
	VolumeName string `protobuf:"bytes,1,opt,name=volumeName" json:"volumeName,omitempty"`
	Mountpoint string `protobuf:"bytes,2,opt,name=mountpoint" json:"mountpoint,omitempty"`
}

func (m *VolumeMountRequest) Reset()         { *m = VolumeMountRequest{} }
func (m *VolumeMountRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeMountRequest) ProtoMessage()    {}

type VolumeCreateRequest struct {
	VolumeName string `protobuf:"bytes,1,opt,name=volumeName" json:"volumeName,omitempty"`
}

func (m *VolumeCreateRequest) Reset()         { *m = VolumeCreateRequest{} }
func (m *VolumeCreateRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeCreateRequest) ProtoMessage()    {}

func init() {
}
