// Code generated by protoc-gen-gogo.
// source: bazil.org/bazil/control/wire/volume.proto
// DO NOT EDIT!

/*
Package wire is a generated protocol buffer package.

It is generated from these files:
	bazil.org/bazil/control/wire/volume.proto

It has these top-level messages:
	VolumeMountRequest
	VolumeCreateRequest
*/
package wire

import proto "github.com/gogo/protobuf/proto"
import math "math"

// discarding unused import gogoproto "github.com/gogo/protobuf/gogoproto/gogo.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type VolumeMountRequest struct {
	VolumeName       string `protobuf:"bytes,1,req,name=volumeName" json:"volumeName"`
	Mountpoint       string `protobuf:"bytes,2,req,name=mountpoint" json:"mountpoint"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *VolumeMountRequest) Reset()         { *m = VolumeMountRequest{} }
func (m *VolumeMountRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeMountRequest) ProtoMessage()    {}

func (m *VolumeMountRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *VolumeMountRequest) GetMountpoint() string {
	if m != nil {
		return m.Mountpoint
	}
	return ""
}

type VolumeCreateRequest struct {
	VolumeName       string `protobuf:"bytes,1,req,name=volumeName" json:"volumeName"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *VolumeCreateRequest) Reset()         { *m = VolumeCreateRequest{} }
func (m *VolumeCreateRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeCreateRequest) ProtoMessage()    {}

func (m *VolumeCreateRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func init() {
}
