// Code generated by protoc-gen-go.
// source: bazil.org/bazil/server/control/wire/peer.proto
// DO NOT EDIT!

package wire

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type PeerAddRequest struct {
	// Must be exactly 32 bytes long.
	Pub []byte `protobuf:"bytes,2,opt,name=pub,proto3" json:"pub,omitempty"`
}

func (m *PeerAddRequest) Reset()         { *m = PeerAddRequest{} }
func (m *PeerAddRequest) String() string { return proto.CompactTextString(m) }
func (*PeerAddRequest) ProtoMessage()    {}

type PeerAddResponse struct {
}

func (m *PeerAddResponse) Reset()         { *m = PeerAddResponse{} }
func (m *PeerAddResponse) String() string { return proto.CompactTextString(m) }
func (*PeerAddResponse) ProtoMessage()    {}

type PeerLocationSetRequest struct {
	// Must be exactly 32 bytes long.
	Pub    []byte `protobuf:"bytes,1,opt,name=pub,proto3" json:"pub,omitempty"`
	Netloc string `protobuf:"bytes,2,opt,name=netloc" json:"netloc,omitempty"`
}

func (m *PeerLocationSetRequest) Reset()         { *m = PeerLocationSetRequest{} }
func (m *PeerLocationSetRequest) String() string { return proto.CompactTextString(m) }
func (*PeerLocationSetRequest) ProtoMessage()    {}

type PeerLocationSetResponse struct {
}

func (m *PeerLocationSetResponse) Reset()         { *m = PeerLocationSetResponse{} }
func (m *PeerLocationSetResponse) String() string { return proto.CompactTextString(m) }
func (*PeerLocationSetResponse) ProtoMessage()    {}

type PeerStorageAllowRequest struct {
	// Must be exactly 32 bytes long.
	Pub     []byte `protobuf:"bytes,1,opt,name=pub,proto3" json:"pub,omitempty"`
	Backend string `protobuf:"bytes,2,opt,name=backend" json:"backend,omitempty"`
}

func (m *PeerStorageAllowRequest) Reset()         { *m = PeerStorageAllowRequest{} }
func (m *PeerStorageAllowRequest) String() string { return proto.CompactTextString(m) }
func (*PeerStorageAllowRequest) ProtoMessage()    {}

type PeerStorageAllowResponse struct {
}

func (m *PeerStorageAllowResponse) Reset()         { *m = PeerStorageAllowResponse{} }
func (m *PeerStorageAllowResponse) String() string { return proto.CompactTextString(m) }
func (*PeerStorageAllowResponse) ProtoMessage()    {}

type PeerVolumeAllowRequest struct {
	// Must be exactly 32 bytes long.
	Pub        []byte `protobuf:"bytes,1,opt,name=pub,proto3" json:"pub,omitempty"`
	VolumeName string `protobuf:"bytes,2,opt,name=volumeName" json:"volumeName,omitempty"`
}

func (m *PeerVolumeAllowRequest) Reset()         { *m = PeerVolumeAllowRequest{} }
func (m *PeerVolumeAllowRequest) String() string { return proto.CompactTextString(m) }
func (*PeerVolumeAllowRequest) ProtoMessage()    {}

type PeerVolumeAllowResponse struct {
}

func (m *PeerVolumeAllowResponse) Reset()         { *m = PeerVolumeAllowResponse{} }
func (m *PeerVolumeAllowResponse) String() string { return proto.CompactTextString(m) }
func (*PeerVolumeAllowResponse) ProtoMessage()    {}

func init() {
}
