// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bazil.org/bazil/server/control/wire/peer.proto

package wire

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PeerAddRequest struct {
	// Must be exactly 32 bytes long.
	Pub                  []byte   `protobuf:"bytes,2,opt,name=pub,proto3" json:"pub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerAddRequest) Reset()         { *m = PeerAddRequest{} }
func (m *PeerAddRequest) String() string { return proto.CompactTextString(m) }
func (*PeerAddRequest) ProtoMessage()    {}
func (*PeerAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a982a125f60130, []int{0}
}

func (m *PeerAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerAddRequest.Unmarshal(m, b)
}
func (m *PeerAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerAddRequest.Marshal(b, m, deterministic)
}
func (m *PeerAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerAddRequest.Merge(m, src)
}
func (m *PeerAddRequest) XXX_Size() int {
	return xxx_messageInfo_PeerAddRequest.Size(m)
}
func (m *PeerAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerAddRequest proto.InternalMessageInfo

func (m *PeerAddRequest) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

type PeerAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerAddResponse) Reset()         { *m = PeerAddResponse{} }
func (m *PeerAddResponse) String() string { return proto.CompactTextString(m) }
func (*PeerAddResponse) ProtoMessage()    {}
func (*PeerAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a982a125f60130, []int{1}
}

func (m *PeerAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerAddResponse.Unmarshal(m, b)
}
func (m *PeerAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerAddResponse.Marshal(b, m, deterministic)
}
func (m *PeerAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerAddResponse.Merge(m, src)
}
func (m *PeerAddResponse) XXX_Size() int {
	return xxx_messageInfo_PeerAddResponse.Size(m)
}
func (m *PeerAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeerAddResponse proto.InternalMessageInfo

type PeerLocationSetRequest struct {
	// Must be exactly 32 bytes long.
	Pub                  []byte   `protobuf:"bytes,1,opt,name=pub,proto3" json:"pub,omitempty"`
	Netloc               string   `protobuf:"bytes,2,opt,name=netloc,proto3" json:"netloc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerLocationSetRequest) Reset()         { *m = PeerLocationSetRequest{} }
func (m *PeerLocationSetRequest) String() string { return proto.CompactTextString(m) }
func (*PeerLocationSetRequest) ProtoMessage()    {}
func (*PeerLocationSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a982a125f60130, []int{2}
}

func (m *PeerLocationSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerLocationSetRequest.Unmarshal(m, b)
}
func (m *PeerLocationSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerLocationSetRequest.Marshal(b, m, deterministic)
}
func (m *PeerLocationSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerLocationSetRequest.Merge(m, src)
}
func (m *PeerLocationSetRequest) XXX_Size() int {
	return xxx_messageInfo_PeerLocationSetRequest.Size(m)
}
func (m *PeerLocationSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerLocationSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerLocationSetRequest proto.InternalMessageInfo

func (m *PeerLocationSetRequest) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *PeerLocationSetRequest) GetNetloc() string {
	if m != nil {
		return m.Netloc
	}
	return ""
}

type PeerLocationSetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerLocationSetResponse) Reset()         { *m = PeerLocationSetResponse{} }
func (m *PeerLocationSetResponse) String() string { return proto.CompactTextString(m) }
func (*PeerLocationSetResponse) ProtoMessage()    {}
func (*PeerLocationSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a982a125f60130, []int{3}
}

func (m *PeerLocationSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerLocationSetResponse.Unmarshal(m, b)
}
func (m *PeerLocationSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerLocationSetResponse.Marshal(b, m, deterministic)
}
func (m *PeerLocationSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerLocationSetResponse.Merge(m, src)
}
func (m *PeerLocationSetResponse) XXX_Size() int {
	return xxx_messageInfo_PeerLocationSetResponse.Size(m)
}
func (m *PeerLocationSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerLocationSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeerLocationSetResponse proto.InternalMessageInfo

type PeerStorageAllowRequest struct {
	// Must be exactly 32 bytes long.
	Pub                  []byte   `protobuf:"bytes,1,opt,name=pub,proto3" json:"pub,omitempty"`
	Backend              string   `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerStorageAllowRequest) Reset()         { *m = PeerStorageAllowRequest{} }
func (m *PeerStorageAllowRequest) String() string { return proto.CompactTextString(m) }
func (*PeerStorageAllowRequest) ProtoMessage()    {}
func (*PeerStorageAllowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a982a125f60130, []int{4}
}

func (m *PeerStorageAllowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerStorageAllowRequest.Unmarshal(m, b)
}
func (m *PeerStorageAllowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerStorageAllowRequest.Marshal(b, m, deterministic)
}
func (m *PeerStorageAllowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerStorageAllowRequest.Merge(m, src)
}
func (m *PeerStorageAllowRequest) XXX_Size() int {
	return xxx_messageInfo_PeerStorageAllowRequest.Size(m)
}
func (m *PeerStorageAllowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerStorageAllowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerStorageAllowRequest proto.InternalMessageInfo

func (m *PeerStorageAllowRequest) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *PeerStorageAllowRequest) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

type PeerStorageAllowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerStorageAllowResponse) Reset()         { *m = PeerStorageAllowResponse{} }
func (m *PeerStorageAllowResponse) String() string { return proto.CompactTextString(m) }
func (*PeerStorageAllowResponse) ProtoMessage()    {}
func (*PeerStorageAllowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a982a125f60130, []int{5}
}

func (m *PeerStorageAllowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerStorageAllowResponse.Unmarshal(m, b)
}
func (m *PeerStorageAllowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerStorageAllowResponse.Marshal(b, m, deterministic)
}
func (m *PeerStorageAllowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerStorageAllowResponse.Merge(m, src)
}
func (m *PeerStorageAllowResponse) XXX_Size() int {
	return xxx_messageInfo_PeerStorageAllowResponse.Size(m)
}
func (m *PeerStorageAllowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerStorageAllowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeerStorageAllowResponse proto.InternalMessageInfo

type PeerVolumeAllowRequest struct {
	// Must be exactly 32 bytes long.
	Pub                  []byte   `protobuf:"bytes,1,opt,name=pub,proto3" json:"pub,omitempty"`
	VolumeName           string   `protobuf:"bytes,2,opt,name=volumeName,proto3" json:"volumeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerVolumeAllowRequest) Reset()         { *m = PeerVolumeAllowRequest{} }
func (m *PeerVolumeAllowRequest) String() string { return proto.CompactTextString(m) }
func (*PeerVolumeAllowRequest) ProtoMessage()    {}
func (*PeerVolumeAllowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a982a125f60130, []int{6}
}

func (m *PeerVolumeAllowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerVolumeAllowRequest.Unmarshal(m, b)
}
func (m *PeerVolumeAllowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerVolumeAllowRequest.Marshal(b, m, deterministic)
}
func (m *PeerVolumeAllowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerVolumeAllowRequest.Merge(m, src)
}
func (m *PeerVolumeAllowRequest) XXX_Size() int {
	return xxx_messageInfo_PeerVolumeAllowRequest.Size(m)
}
func (m *PeerVolumeAllowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerVolumeAllowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerVolumeAllowRequest proto.InternalMessageInfo

func (m *PeerVolumeAllowRequest) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *PeerVolumeAllowRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

type PeerVolumeAllowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerVolumeAllowResponse) Reset()         { *m = PeerVolumeAllowResponse{} }
func (m *PeerVolumeAllowResponse) String() string { return proto.CompactTextString(m) }
func (*PeerVolumeAllowResponse) ProtoMessage()    {}
func (*PeerVolumeAllowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a982a125f60130, []int{7}
}

func (m *PeerVolumeAllowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerVolumeAllowResponse.Unmarshal(m, b)
}
func (m *PeerVolumeAllowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerVolumeAllowResponse.Marshal(b, m, deterministic)
}
func (m *PeerVolumeAllowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerVolumeAllowResponse.Merge(m, src)
}
func (m *PeerVolumeAllowResponse) XXX_Size() int {
	return xxx_messageInfo_PeerVolumeAllowResponse.Size(m)
}
func (m *PeerVolumeAllowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerVolumeAllowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeerVolumeAllowResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PeerAddRequest)(nil), "bazil.control.PeerAddRequest")
	proto.RegisterType((*PeerAddResponse)(nil), "bazil.control.PeerAddResponse")
	proto.RegisterType((*PeerLocationSetRequest)(nil), "bazil.control.PeerLocationSetRequest")
	proto.RegisterType((*PeerLocationSetResponse)(nil), "bazil.control.PeerLocationSetResponse")
	proto.RegisterType((*PeerStorageAllowRequest)(nil), "bazil.control.PeerStorageAllowRequest")
	proto.RegisterType((*PeerStorageAllowResponse)(nil), "bazil.control.PeerStorageAllowResponse")
	proto.RegisterType((*PeerVolumeAllowRequest)(nil), "bazil.control.PeerVolumeAllowRequest")
	proto.RegisterType((*PeerVolumeAllowResponse)(nil), "bazil.control.PeerVolumeAllowResponse")
}

func init() {
	proto.RegisterFile("bazil.org/bazil/server/control/wire/peer.proto", fileDescriptor_a7a982a125f60130)
}

var fileDescriptor_a7a982a125f60130 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x80, 0x59, 0x95, 0x8a, 0x83, 0xbf, 0x3d, 0xac, 0xd5, 0x83, 0x48, 0x4e, 0x9e, 0x9a, 0x83,
	0x4f, 0xb0, 0x0b, 0x5e, 0x44, 0x44, 0xba, 0xe0, 0xc1, 0x5b, 0xda, 0x0e, 0x4b, 0x31, 0x9b, 0x89,
	0x93, 0x74, 0x17, 0x7c, 0x7a, 0x69, 0x92, 0x5d, 0xd4, 0x22, 0xde, 0xe6, 0xf7, 0xfb, 0x98, 0x04,
	0xca, 0x5a, 0x7d, 0x76, 0xba, 0x24, 0x5e, 0xca, 0x10, 0x49, 0x87, 0xbc, 0x46, 0x96, 0x0d, 0x19,
	0xcf, 0xa4, 0xe5, 0xa6, 0x63, 0x94, 0x16, 0x91, 0x4b, 0xcb, 0xe4, 0x29, 0x3f, 0x89, 0xf3, 0xa9,
	0x2d, 0x04, 0x9c, 0xbe, 0x20, 0xf2, 0xac, 0x6d, 0x2b, 0xfc, 0xe8, 0xd1, 0xf9, 0xfc, 0x1c, 0xf6,
	0x6d, 0x5f, 0x17, 0x7b, 0xb7, 0x93, 0xbb, 0xe3, 0x6a, 0x08, 0xc5, 0x05, 0x9c, 0xed, 0x66, 0x9c,
	0x25, 0xe3, 0x50, 0xcc, 0x61, 0x3a, 0x94, 0x9e, 0xa8, 0x51, 0xbe, 0x23, 0xb3, 0x40, 0xff, 0x6b,
	0x7d, 0xb2, 0x5b, 0xcf, 0xa7, 0x90, 0x19, 0xf4, 0x9a, 0x9a, 0xc0, 0x3c, 0xaa, 0x52, 0x26, 0xae,
	0xe0, 0x72, 0xc4, 0x48, 0xf8, 0x87, 0xd8, 0x5a, 0x78, 0x62, 0xb5, 0xc4, 0x99, 0xd6, 0xb4, 0xf9,
	0x9b, 0x5f, 0xc0, 0x61, 0xad, 0x9a, 0x77, 0x34, 0x6d, 0x12, 0x6c, 0x53, 0x71, 0x0d, 0xc5, 0x18,
	0x93, 0x14, 0x8f, 0xf1, 0x82, 0x57, 0xd2, 0xfd, 0xea, 0x3f, 0xc3, 0x0d, 0xc0, 0x3a, 0xcc, 0x3d,
	0xab, 0x15, 0x26, 0xc9, 0xb7, 0xca, 0xf6, 0x92, 0x1f, 0xac, 0xa8, 0x99, 0x67, 0x6f, 0x07, 0xc3,
	0x0f, 0xd4, 0x59, 0x78, 0xfd, 0xfb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0xf1, 0x7b, 0xeb,
	0xaf, 0x01, 0x00, 0x00,
}
