// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bazil.org/bazil/server/control/wire/publickey.proto

package wire

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PublicKeyGetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeyGetRequest) Reset()         { *m = PublicKeyGetRequest{} }
func (m *PublicKeyGetRequest) String() string { return proto.CompactTextString(m) }
func (*PublicKeyGetRequest) ProtoMessage()    {}
func (*PublicKeyGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10279264ffc71856, []int{0}
}

func (m *PublicKeyGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyGetRequest.Unmarshal(m, b)
}
func (m *PublicKeyGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyGetRequest.Marshal(b, m, deterministic)
}
func (m *PublicKeyGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyGetRequest.Merge(m, src)
}
func (m *PublicKeyGetRequest) XXX_Size() int {
	return xxx_messageInfo_PublicKeyGetRequest.Size(m)
}
func (m *PublicKeyGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyGetRequest proto.InternalMessageInfo

type PublicKeyGetResponse struct {
	// Exactly 32 bytes long.
	Pub                  []byte   `protobuf:"bytes,1,opt,name=pub,proto3" json:"pub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeyGetResponse) Reset()         { *m = PublicKeyGetResponse{} }
func (m *PublicKeyGetResponse) String() string { return proto.CompactTextString(m) }
func (*PublicKeyGetResponse) ProtoMessage()    {}
func (*PublicKeyGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10279264ffc71856, []int{1}
}

func (m *PublicKeyGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyGetResponse.Unmarshal(m, b)
}
func (m *PublicKeyGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyGetResponse.Marshal(b, m, deterministic)
}
func (m *PublicKeyGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyGetResponse.Merge(m, src)
}
func (m *PublicKeyGetResponse) XXX_Size() int {
	return xxx_messageInfo_PublicKeyGetResponse.Size(m)
}
func (m *PublicKeyGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyGetResponse proto.InternalMessageInfo

func (m *PublicKeyGetResponse) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func init() {
	proto.RegisterType((*PublicKeyGetRequest)(nil), "bazil.control.PublicKeyGetRequest")
	proto.RegisterType((*PublicKeyGetResponse)(nil), "bazil.control.PublicKeyGetResponse")
}

func init() {
	proto.RegisterFile("bazil.org/bazil/server/control/wire/publickey.proto", fileDescriptor_10279264ffc71856)
}

var fileDescriptor_10279264ffc71856 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4e, 0x4a, 0xac, 0xca,
	0xcc, 0xd1, 0xcb, 0x2f, 0x4a, 0xd7, 0x07, 0xb3, 0xf4, 0x8b, 0x53, 0x8b, 0xca, 0x52, 0x8b, 0xf4,
	0x93, 0xf3, 0xf3, 0x4a, 0x8a, 0xf2, 0x73, 0xf4, 0xcb, 0x33, 0x8b, 0x52, 0xf5, 0x0b, 0x4a, 0x93,
	0x72, 0x32, 0x93, 0xb3, 0x53, 0x2b, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x78, 0x21, 0x9a,
	0xa0, 0x6a, 0x94, 0x44, 0xb9, 0x84, 0x03, 0xc0, 0x2a, 0xbc, 0x53, 0x2b, 0xdd, 0x53, 0x4b, 0x82,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0x34, 0xb8, 0x44, 0x50, 0x85, 0x8b, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x85, 0x04, 0xb8, 0x98, 0x0b, 0x4a, 0x93, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82,
	0x40, 0x4c, 0x27, 0xb6, 0x28, 0x16, 0x90, 0x3d, 0x49, 0x6c, 0x60, 0xe3, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x82, 0x46, 0x57, 0xda, 0x95, 0x00, 0x00, 0x00,
}
