// Code generated by protoc-gen-go.
// source: bazil.org/bazil/server/control/wire/publickey.proto
// DO NOT EDIT!

package wire

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type PublicKeyGetRequest struct {
}

func (m *PublicKeyGetRequest) Reset()         { *m = PublicKeyGetRequest{} }
func (m *PublicKeyGetRequest) String() string { return proto.CompactTextString(m) }
func (*PublicKeyGetRequest) ProtoMessage()    {}

type PublicKeyGetResponse struct {
	// Exactly 32 bytes long.
	Pub []byte `protobuf:"bytes,1,opt,name=pub,proto3" json:"pub,omitempty"`
}

func (m *PublicKeyGetResponse) Reset()         { *m = PublicKeyGetResponse{} }
func (m *PublicKeyGetResponse) String() string { return proto.CompactTextString(m) }
func (*PublicKeyGetResponse) ProtoMessage()    {}
