// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bazil.org/bazil/server/control/wire/sharing.proto

package wire

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SharingKeyAddRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Must be exactly 32 bytes long.
	Secret               []byte   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharingKeyAddRequest) Reset()         { *m = SharingKeyAddRequest{} }
func (m *SharingKeyAddRequest) String() string { return proto.CompactTextString(m) }
func (*SharingKeyAddRequest) ProtoMessage()    {}
func (*SharingKeyAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca3dca729318981e, []int{0}
}

func (m *SharingKeyAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharingKeyAddRequest.Unmarshal(m, b)
}
func (m *SharingKeyAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharingKeyAddRequest.Marshal(b, m, deterministic)
}
func (m *SharingKeyAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharingKeyAddRequest.Merge(m, src)
}
func (m *SharingKeyAddRequest) XXX_Size() int {
	return xxx_messageInfo_SharingKeyAddRequest.Size(m)
}
func (m *SharingKeyAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SharingKeyAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SharingKeyAddRequest proto.InternalMessageInfo

func (m *SharingKeyAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SharingKeyAddRequest) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

type SharingKeyAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharingKeyAddResponse) Reset()         { *m = SharingKeyAddResponse{} }
func (m *SharingKeyAddResponse) String() string { return proto.CompactTextString(m) }
func (*SharingKeyAddResponse) ProtoMessage()    {}
func (*SharingKeyAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca3dca729318981e, []int{1}
}

func (m *SharingKeyAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharingKeyAddResponse.Unmarshal(m, b)
}
func (m *SharingKeyAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharingKeyAddResponse.Marshal(b, m, deterministic)
}
func (m *SharingKeyAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharingKeyAddResponse.Merge(m, src)
}
func (m *SharingKeyAddResponse) XXX_Size() int {
	return xxx_messageInfo_SharingKeyAddResponse.Size(m)
}
func (m *SharingKeyAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SharingKeyAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SharingKeyAddResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SharingKeyAddRequest)(nil), "bazil.control.SharingKeyAddRequest")
	proto.RegisterType((*SharingKeyAddResponse)(nil), "bazil.control.SharingKeyAddResponse")
}

func init() {
	proto.RegisterFile("bazil.org/bazil/server/control/wire/sharing.proto", fileDescriptor_ca3dca729318981e)
}

var fileDescriptor_ca3dca729318981e = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4c, 0x4a, 0xac, 0xca,
	0xcc, 0xd1, 0xcb, 0x2f, 0x4a, 0xd7, 0x07, 0xb3, 0xf4, 0x8b, 0x53, 0x8b, 0xca, 0x52, 0x8b, 0xf4,
	0x93, 0xf3, 0xf3, 0x4a, 0x8a, 0xf2, 0x73, 0xf4, 0xcb, 0x33, 0x8b, 0x52, 0xf5, 0x8b, 0x33, 0x12,
	0x8b, 0x32, 0xf3, 0xd2, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x78, 0x21, 0x5a, 0xa0, 0x2a,
	0x94, 0x9c, 0xb8, 0x44, 0x82, 0x21, 0xf2, 0xde, 0xa9, 0x95, 0x8e, 0x29, 0x29, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x18, 0x17, 0x5b, 0x71, 0x6a, 0x72, 0x51, 0x6a, 0x89, 0x04,
	0x93, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x94, 0xa7, 0x24, 0xce, 0x25, 0x8a, 0x66, 0x46, 0x71, 0x41,
	0x7e, 0x5e, 0x71, 0xaa, 0x13, 0x5b, 0x14, 0x0b, 0xc8, 0x05, 0x49, 0x6c, 0x60, 0xab, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x52, 0x9a, 0xa6, 0xaf, 0x00, 0x00, 0x00,
}
