// Code generated by protoc-gen-go.
// source: bazil.org/bazil/server/control/wire/sharing.proto
// DO NOT EDIT!

package wire

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type SharingKeyAddRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Must be exactly 32 bytes long.
	Secret []byte `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (m *SharingKeyAddRequest) Reset()         { *m = SharingKeyAddRequest{} }
func (m *SharingKeyAddRequest) String() string { return proto.CompactTextString(m) }
func (*SharingKeyAddRequest) ProtoMessage()    {}

type SharingKeyAddResponse struct {
}

func (m *SharingKeyAddResponse) Reset()         { *m = SharingKeyAddResponse{} }
func (m *SharingKeyAddResponse) String() string { return proto.CompactTextString(m) }
func (*SharingKeyAddResponse) ProtoMessage()    {}
