// Code generated by protoc-gen-go.
// source: bazil.org/bazil/server/control/wire/volume.proto
// DO NOT EDIT!

package wire

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type VolumeMountRequest struct {
	VolumeName string `protobuf:"bytes,1,opt,name=volumeName" json:"volumeName,omitempty"`
	Mountpoint string `protobuf:"bytes,2,opt,name=mountpoint" json:"mountpoint,omitempty"`
}

func (m *VolumeMountRequest) Reset()         { *m = VolumeMountRequest{} }
func (m *VolumeMountRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeMountRequest) ProtoMessage()    {}

type VolumeMountResponse struct {
}

func (m *VolumeMountResponse) Reset()         { *m = VolumeMountResponse{} }
func (m *VolumeMountResponse) String() string { return proto.CompactTextString(m) }
func (*VolumeMountResponse) ProtoMessage()    {}

type VolumeCreateRequest struct {
	VolumeName     string `protobuf:"bytes,1,opt,name=volumeName" json:"volumeName,omitempty"`
	Backend        string `protobuf:"bytes,2,opt,name=backend" json:"backend,omitempty"`
	SharingKeyName string `protobuf:"bytes,3,opt,name=sharingKeyName" json:"sharingKeyName,omitempty"`
}

func (m *VolumeCreateRequest) Reset()         { *m = VolumeCreateRequest{} }
func (m *VolumeCreateRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeCreateRequest) ProtoMessage()    {}

type VolumeCreateResponse struct {
}

func (m *VolumeCreateResponse) Reset()         { *m = VolumeCreateResponse{} }
func (m *VolumeCreateResponse) String() string { return proto.CompactTextString(m) }
func (*VolumeCreateResponse) ProtoMessage()    {}

type VolumeConnectRequest struct {
	// Must be exactly 32 bytes long.
	Pub             []byte `protobuf:"bytes,1,opt,name=pub,proto3" json:"pub,omitempty"`
	VolumeName      string `protobuf:"bytes,2,opt,name=volumeName" json:"volumeName,omitempty"`
	LocalVolumeName string `protobuf:"bytes,3,opt,name=localVolumeName" json:"localVolumeName,omitempty"`
	Backend         string `protobuf:"bytes,4,opt,name=backend" json:"backend,omitempty"`
	SharingKeyName  string `protobuf:"bytes,5,opt,name=sharingKeyName" json:"sharingKeyName,omitempty"`
}

func (m *VolumeConnectRequest) Reset()         { *m = VolumeConnectRequest{} }
func (m *VolumeConnectRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeConnectRequest) ProtoMessage()    {}

type VolumeConnectResponse struct {
}

func (m *VolumeConnectResponse) Reset()         { *m = VolumeConnectResponse{} }
func (m *VolumeConnectResponse) String() string { return proto.CompactTextString(m) }
func (*VolumeConnectResponse) ProtoMessage()    {}

type VolumeStorageAddRequest struct {
	VolumeName     string `protobuf:"bytes,1,opt,name=volumeName" json:"volumeName,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Backend        string `protobuf:"bytes,3,opt,name=backend" json:"backend,omitempty"`
	SharingKeyName string `protobuf:"bytes,4,opt,name=sharingKeyName" json:"sharingKeyName,omitempty"`
}

func (m *VolumeStorageAddRequest) Reset()         { *m = VolumeStorageAddRequest{} }
func (m *VolumeStorageAddRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeStorageAddRequest) ProtoMessage()    {}

type VolumeStorageAddResponse struct {
}

func (m *VolumeStorageAddResponse) Reset()         { *m = VolumeStorageAddResponse{} }
func (m *VolumeStorageAddResponse) String() string { return proto.CompactTextString(m) }
func (*VolumeStorageAddResponse) ProtoMessage()    {}

type VolumeSyncRequest struct {
	VolumeName string `protobuf:"bytes,1,opt,name=volumeName" json:"volumeName,omitempty"`
	// Must be exactly 32 bytes long.
	Pub  []byte `protobuf:"bytes,2,opt,name=pub,proto3" json:"pub,omitempty"`
	Path string `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
}

func (m *VolumeSyncRequest) Reset()         { *m = VolumeSyncRequest{} }
func (m *VolumeSyncRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeSyncRequest) ProtoMessage()    {}

type VolumeSyncResponse struct {
}

func (m *VolumeSyncResponse) Reset()         { *m = VolumeSyncResponse{} }
func (m *VolumeSyncResponse) String() string { return proto.CompactTextString(m) }
func (*VolumeSyncResponse) ProtoMessage()    {}
