// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bazil.org/bazil/server/control/wire/volume.proto

package wire

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VolumeMountRequest struct {
	VolumeName           string   `protobuf:"bytes,1,opt,name=volumeName,proto3" json:"volumeName,omitempty"`
	Mountpoint           string   `protobuf:"bytes,2,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeMountRequest) Reset()         { *m = VolumeMountRequest{} }
func (m *VolumeMountRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeMountRequest) ProtoMessage()    {}
func (*VolumeMountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98399f9af98d1082, []int{0}
}

func (m *VolumeMountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeMountRequest.Unmarshal(m, b)
}
func (m *VolumeMountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeMountRequest.Marshal(b, m, deterministic)
}
func (m *VolumeMountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeMountRequest.Merge(m, src)
}
func (m *VolumeMountRequest) XXX_Size() int {
	return xxx_messageInfo_VolumeMountRequest.Size(m)
}
func (m *VolumeMountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeMountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeMountRequest proto.InternalMessageInfo

func (m *VolumeMountRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *VolumeMountRequest) GetMountpoint() string {
	if m != nil {
		return m.Mountpoint
	}
	return ""
}

type VolumeMountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeMountResponse) Reset()         { *m = VolumeMountResponse{} }
func (m *VolumeMountResponse) String() string { return proto.CompactTextString(m) }
func (*VolumeMountResponse) ProtoMessage()    {}
func (*VolumeMountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98399f9af98d1082, []int{1}
}

func (m *VolumeMountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeMountResponse.Unmarshal(m, b)
}
func (m *VolumeMountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeMountResponse.Marshal(b, m, deterministic)
}
func (m *VolumeMountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeMountResponse.Merge(m, src)
}
func (m *VolumeMountResponse) XXX_Size() int {
	return xxx_messageInfo_VolumeMountResponse.Size(m)
}
func (m *VolumeMountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeMountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeMountResponse proto.InternalMessageInfo

type VolumeCreateRequest struct {
	VolumeName           string   `protobuf:"bytes,1,opt,name=volumeName,proto3" json:"volumeName,omitempty"`
	Backend              string   `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	SharingKeyName       string   `protobuf:"bytes,3,opt,name=sharingKeyName,proto3" json:"sharingKeyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeCreateRequest) Reset()         { *m = VolumeCreateRequest{} }
func (m *VolumeCreateRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeCreateRequest) ProtoMessage()    {}
func (*VolumeCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98399f9af98d1082, []int{2}
}

func (m *VolumeCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeCreateRequest.Unmarshal(m, b)
}
func (m *VolumeCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeCreateRequest.Marshal(b, m, deterministic)
}
func (m *VolumeCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeCreateRequest.Merge(m, src)
}
func (m *VolumeCreateRequest) XXX_Size() int {
	return xxx_messageInfo_VolumeCreateRequest.Size(m)
}
func (m *VolumeCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeCreateRequest proto.InternalMessageInfo

func (m *VolumeCreateRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *VolumeCreateRequest) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *VolumeCreateRequest) GetSharingKeyName() string {
	if m != nil {
		return m.SharingKeyName
	}
	return ""
}

type VolumeCreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeCreateResponse) Reset()         { *m = VolumeCreateResponse{} }
func (m *VolumeCreateResponse) String() string { return proto.CompactTextString(m) }
func (*VolumeCreateResponse) ProtoMessage()    {}
func (*VolumeCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98399f9af98d1082, []int{3}
}

func (m *VolumeCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeCreateResponse.Unmarshal(m, b)
}
func (m *VolumeCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeCreateResponse.Marshal(b, m, deterministic)
}
func (m *VolumeCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeCreateResponse.Merge(m, src)
}
func (m *VolumeCreateResponse) XXX_Size() int {
	return xxx_messageInfo_VolumeCreateResponse.Size(m)
}
func (m *VolumeCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeCreateResponse proto.InternalMessageInfo

type VolumeConnectRequest struct {
	// Must be exactly 32 bytes long.
	Pub                  []byte   `protobuf:"bytes,1,opt,name=pub,proto3" json:"pub,omitempty"`
	VolumeName           string   `protobuf:"bytes,2,opt,name=volumeName,proto3" json:"volumeName,omitempty"`
	LocalVolumeName      string   `protobuf:"bytes,3,opt,name=localVolumeName,proto3" json:"localVolumeName,omitempty"`
	Backend              string   `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	SharingKeyName       string   `protobuf:"bytes,5,opt,name=sharingKeyName,proto3" json:"sharingKeyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeConnectRequest) Reset()         { *m = VolumeConnectRequest{} }
func (m *VolumeConnectRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeConnectRequest) ProtoMessage()    {}
func (*VolumeConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98399f9af98d1082, []int{4}
}

func (m *VolumeConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeConnectRequest.Unmarshal(m, b)
}
func (m *VolumeConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeConnectRequest.Marshal(b, m, deterministic)
}
func (m *VolumeConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeConnectRequest.Merge(m, src)
}
func (m *VolumeConnectRequest) XXX_Size() int {
	return xxx_messageInfo_VolumeConnectRequest.Size(m)
}
func (m *VolumeConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeConnectRequest proto.InternalMessageInfo

func (m *VolumeConnectRequest) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *VolumeConnectRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *VolumeConnectRequest) GetLocalVolumeName() string {
	if m != nil {
		return m.LocalVolumeName
	}
	return ""
}

func (m *VolumeConnectRequest) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *VolumeConnectRequest) GetSharingKeyName() string {
	if m != nil {
		return m.SharingKeyName
	}
	return ""
}

type VolumeConnectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeConnectResponse) Reset()         { *m = VolumeConnectResponse{} }
func (m *VolumeConnectResponse) String() string { return proto.CompactTextString(m) }
func (*VolumeConnectResponse) ProtoMessage()    {}
func (*VolumeConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98399f9af98d1082, []int{5}
}

func (m *VolumeConnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeConnectResponse.Unmarshal(m, b)
}
func (m *VolumeConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeConnectResponse.Marshal(b, m, deterministic)
}
func (m *VolumeConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeConnectResponse.Merge(m, src)
}
func (m *VolumeConnectResponse) XXX_Size() int {
	return xxx_messageInfo_VolumeConnectResponse.Size(m)
}
func (m *VolumeConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeConnectResponse proto.InternalMessageInfo

type VolumeStorageAddRequest struct {
	VolumeName           string   `protobuf:"bytes,1,opt,name=volumeName,proto3" json:"volumeName,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Backend              string   `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	SharingKeyName       string   `protobuf:"bytes,4,opt,name=sharingKeyName,proto3" json:"sharingKeyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeStorageAddRequest) Reset()         { *m = VolumeStorageAddRequest{} }
func (m *VolumeStorageAddRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeStorageAddRequest) ProtoMessage()    {}
func (*VolumeStorageAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98399f9af98d1082, []int{6}
}

func (m *VolumeStorageAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeStorageAddRequest.Unmarshal(m, b)
}
func (m *VolumeStorageAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeStorageAddRequest.Marshal(b, m, deterministic)
}
func (m *VolumeStorageAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeStorageAddRequest.Merge(m, src)
}
func (m *VolumeStorageAddRequest) XXX_Size() int {
	return xxx_messageInfo_VolumeStorageAddRequest.Size(m)
}
func (m *VolumeStorageAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeStorageAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeStorageAddRequest proto.InternalMessageInfo

func (m *VolumeStorageAddRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *VolumeStorageAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VolumeStorageAddRequest) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *VolumeStorageAddRequest) GetSharingKeyName() string {
	if m != nil {
		return m.SharingKeyName
	}
	return ""
}

type VolumeStorageAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeStorageAddResponse) Reset()         { *m = VolumeStorageAddResponse{} }
func (m *VolumeStorageAddResponse) String() string { return proto.CompactTextString(m) }
func (*VolumeStorageAddResponse) ProtoMessage()    {}
func (*VolumeStorageAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98399f9af98d1082, []int{7}
}

func (m *VolumeStorageAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeStorageAddResponse.Unmarshal(m, b)
}
func (m *VolumeStorageAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeStorageAddResponse.Marshal(b, m, deterministic)
}
func (m *VolumeStorageAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeStorageAddResponse.Merge(m, src)
}
func (m *VolumeStorageAddResponse) XXX_Size() int {
	return xxx_messageInfo_VolumeStorageAddResponse.Size(m)
}
func (m *VolumeStorageAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeStorageAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeStorageAddResponse proto.InternalMessageInfo

type VolumeSyncRequest struct {
	VolumeName string `protobuf:"bytes,1,opt,name=volumeName,proto3" json:"volumeName,omitempty"`
	// Must be exactly 32 bytes long.
	Pub                  []byte   `protobuf:"bytes,2,opt,name=pub,proto3" json:"pub,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeSyncRequest) Reset()         { *m = VolumeSyncRequest{} }
func (m *VolumeSyncRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeSyncRequest) ProtoMessage()    {}
func (*VolumeSyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98399f9af98d1082, []int{8}
}

func (m *VolumeSyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeSyncRequest.Unmarshal(m, b)
}
func (m *VolumeSyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeSyncRequest.Marshal(b, m, deterministic)
}
func (m *VolumeSyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeSyncRequest.Merge(m, src)
}
func (m *VolumeSyncRequest) XXX_Size() int {
	return xxx_messageInfo_VolumeSyncRequest.Size(m)
}
func (m *VolumeSyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeSyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeSyncRequest proto.InternalMessageInfo

func (m *VolumeSyncRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *VolumeSyncRequest) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *VolumeSyncRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type VolumeSyncResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeSyncResponse) Reset()         { *m = VolumeSyncResponse{} }
func (m *VolumeSyncResponse) String() string { return proto.CompactTextString(m) }
func (*VolumeSyncResponse) ProtoMessage()    {}
func (*VolumeSyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98399f9af98d1082, []int{9}
}

func (m *VolumeSyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeSyncResponse.Unmarshal(m, b)
}
func (m *VolumeSyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeSyncResponse.Marshal(b, m, deterministic)
}
func (m *VolumeSyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeSyncResponse.Merge(m, src)
}
func (m *VolumeSyncResponse) XXX_Size() int {
	return xxx_messageInfo_VolumeSyncResponse.Size(m)
}
func (m *VolumeSyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeSyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeSyncResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VolumeMountRequest)(nil), "bazil.control.VolumeMountRequest")
	proto.RegisterType((*VolumeMountResponse)(nil), "bazil.control.VolumeMountResponse")
	proto.RegisterType((*VolumeCreateRequest)(nil), "bazil.control.VolumeCreateRequest")
	proto.RegisterType((*VolumeCreateResponse)(nil), "bazil.control.VolumeCreateResponse")
	proto.RegisterType((*VolumeConnectRequest)(nil), "bazil.control.VolumeConnectRequest")
	proto.RegisterType((*VolumeConnectResponse)(nil), "bazil.control.VolumeConnectResponse")
	proto.RegisterType((*VolumeStorageAddRequest)(nil), "bazil.control.VolumeStorageAddRequest")
	proto.RegisterType((*VolumeStorageAddResponse)(nil), "bazil.control.VolumeStorageAddResponse")
	proto.RegisterType((*VolumeSyncRequest)(nil), "bazil.control.VolumeSyncRequest")
	proto.RegisterType((*VolumeSyncResponse)(nil), "bazil.control.VolumeSyncResponse")
}

func init() {
	proto.RegisterFile("bazil.org/bazil/server/control/wire/volume.proto", fileDescriptor_98399f9af98d1082)
}

var fileDescriptor_98399f9af98d1082 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0x53, 0xe8, 0xc7, 0x17, 0x6f, 0xfc, 0x3b, 0x82, 0x34, 0x2e, 0x8c, 0xe9, 0xc2, 0xb0,
	0xa2, 0x26, 0x3e, 0x81, 0xba, 0x34, 0xba, 0x40, 0x43, 0xa2, 0xbb, 0x69, 0xb9, 0x81, 0xc6, 0x32,
	0xb7, 0x4e, 0xa7, 0x10, 0x7c, 0x09, 0x5f, 0xc6, 0x07, 0x34, 0x9d, 0x19, 0x28, 0x14, 0x12, 0xba,
	0xbb, 0x3d, 0xe7, 0xce, 0xdc, 0xdf, 0x99, 0xe9, 0xc0, 0x6d, 0xc8, 0xbf, 0xe3, 0xa4, 0x4f, 0x72,
	0x1c, 0xe8, 0x2a, 0xc8, 0x50, 0xce, 0x50, 0x06, 0x11, 0x09, 0x25, 0x29, 0x09, 0xe6, 0xb1, 0xc4,
	0x60, 0x46, 0x49, 0x3e, 0xc5, 0x7e, 0x2a, 0x49, 0x11, 0x3b, 0x32, 0x2b, 0x6c, 0x83, 0xff, 0x06,
	0x6c, 0xa8, 0xed, 0x67, 0xca, 0x85, 0x1a, 0xe0, 0x57, 0x8e, 0x99, 0x62, 0x57, 0x00, 0x66, 0xd1,
	0x0b, 0x9f, 0xa2, 0xe7, 0x5c, 0x3b, 0xbd, 0x83, 0xc1, 0x9a, 0x52, 0xf8, 0xd3, 0xa2, 0x3f, 0xa5,
	0x58, 0x28, 0xaf, 0x61, 0xfc, 0x52, 0xf1, 0x3b, 0x70, 0xbe, 0xb1, 0x6b, 0x96, 0x92, 0xc8, 0xd0,
	0x9f, 0x2f, 0xe5, 0x47, 0x89, 0x5c, 0x61, 0xdd, 0x69, 0x1e, 0xfc, 0x0f, 0x79, 0xf4, 0x89, 0x62,
	0x64, 0x47, 0x2d, 0x3f, 0xd9, 0x0d, 0x1c, 0x67, 0x13, 0x2e, 0x63, 0x31, 0x7e, 0xc2, 0x85, 0x5e,
	0xdd, 0xd4, 0x0d, 0x15, 0xd5, 0xbf, 0x80, 0xf6, 0xe6, 0x60, 0x0b, 0xf4, 0xeb, 0xac, 0x0c, 0x12,
	0x02, 0xa3, 0xd5, 0x01, 0x9c, 0x42, 0x33, 0xcd, 0x43, 0xcd, 0x72, 0x38, 0x28, 0xca, 0x0a, 0x64,
	0x63, 0x0b, 0xb2, 0x07, 0x27, 0x09, 0x45, 0x3c, 0x19, 0x96, 0x4d, 0x86, 0xa5, 0x2a, 0xaf, 0xc7,
	0x71, 0xf7, 0xc5, 0xf9, 0xb7, 0x33, 0x4e, 0x17, 0x3a, 0x15, 0x6a, 0x9b, 0xe7, 0xc7, 0x81, 0xae,
	0x71, 0x5e, 0x15, 0x49, 0x3e, 0xc6, 0xfb, 0xd1, 0xa8, 0xee, 0x29, 0x33, 0x70, 0x45, 0x19, 0x4d,
	0xd7, 0xeb, 0xa8, 0xcd, 0x7d, 0xa8, 0xee, 0x4e, 0xd4, 0x4b, 0xf0, 0xb6, 0x81, 0x2c, 0xed, 0x3b,
	0x9c, 0x59, 0x6f, 0x21, 0xa2, 0xba, 0x98, 0xf6, 0x66, 0x1a, 0xe5, 0xcd, 0x30, 0x70, 0x53, 0xae,
	0x26, 0x96, 0x50, 0xd7, 0x7e, 0x7b, 0xf9, 0x5b, 0x9b, 0xad, 0xcd, 0xc0, 0x87, 0xd6, 0x87, 0x5b,
	0x3c, 0x88, 0xb0, 0xa5, 0x9f, 0xc2, 0xdd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xa7, 0x69,
	0x48, 0x3e, 0x03, 0x00, 0x00,
}
