// generated by stringer -type=Action; DO NOT EDIT

package clock

import "fmt"

const _Action_name = "InvalidActionCopyNothingConflict"

var _Action_index = [...]uint8{13, 17, 24, 32}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)) {
		return fmt.Sprintf("Action(%d)", i)
	}
	hi := _Action_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Action_index[i-1]
	}
	return _Action_name[lo:hi]
}
