// Code generated by "stringer -type=Action"; DO NOT EDIT.

package clock

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[invalidAction-0]
	_ = x[Copy-1]
	_ = x[Nothing-2]
	_ = x[Conflict-3]
}

const _Action_name = "invalidActionCopyNothingConflict"

var _Action_index = [...]uint8{0, 13, 17, 24, 32}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
