// Code generated by protoc-gen-go.
// source: bazil.org/bazil/fs/wire/dirent.proto
// DO NOT EDIT!

/*
Package wire is a generated protocol buffer package.

It is generated from these files:
	bazil.org/bazil/fs/wire/dirent.proto
	bazil.org/bazil/fs/wire/snap.proto

It has these top-level messages:
	Dirent
	File
	Dir
	Tombstone
*/
package wire

import proto "github.com/golang/protobuf/proto"
import bazil_cas "bazil.org/bazil/cas/wire"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Dirent struct {
	Inode     uint64     `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	File      *File      `protobuf:"bytes,2,opt,name=file" json:"file,omitempty"`
	Dir       *Dir       `protobuf:"bytes,3,opt,name=dir" json:"dir,omitempty"`
	Tombstone *Tombstone `protobuf:"bytes,4,opt,name=tombstone" json:"tombstone,omitempty"`
}

func (m *Dirent) Reset()         { *m = Dirent{} }
func (m *Dirent) String() string { return proto.CompactTextString(m) }
func (*Dirent) ProtoMessage()    {}

func (m *Dirent) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Dirent) GetDir() *Dir {
	if m != nil {
		return m.Dir
	}
	return nil
}

func (m *Dirent) GetTombstone() *Tombstone {
	if m != nil {
		return m.Tombstone
	}
	return nil
}

type File struct {
	Manifest *bazil_cas.Manifest `protobuf:"bytes,1,opt,name=manifest" json:"manifest,omitempty"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}

func (m *File) GetManifest() *bazil_cas.Manifest {
	if m != nil {
		return m.Manifest
	}
	return nil
}

// Dir is a directory stored fully in the database, not persisted
// in objects.
type Dir struct {
}

func (m *Dir) Reset()         { *m = Dir{} }
func (m *Dir) String() string { return proto.CompactTextString(m) }
func (*Dir) ProtoMessage()    {}

type Tombstone struct {
}

func (m *Tombstone) Reset()         { *m = Tombstone{} }
func (m *Tombstone) String() string { return proto.CompactTextString(m) }
func (*Tombstone) ProtoMessage()    {}
