// Code generated by protoc-gen-gogo.
// source: bazil.org/bazil/fs/wire/dirent.proto
// DO NOT EDIT!

/*
	Package wire is a generated protocol buffer package.

	It is generated from these files:
		bazil.org/bazil/fs/wire/dirent.proto
		bazil.org/bazil/fs/wire/snap.proto
		bazil.org/bazil/fs/wire/volume.proto

	It has these top-level messages:
		Dirent
		Type
		File
		Dir
*/
package wire

import proto "github.com/gogo/protobuf/proto"
import math "math"

// discarding unused import gogoproto "github.com/gogo/protobuf/gogoproto/gogo.pb"
import bazil_cas "bazil.org/bazil/cas/wire"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Dirent struct {
	Inode            uint64 `protobuf:"varint,1,req,name=inode" json:"inode"`
	Type             `protobuf:"bytes,2,req,name=type,embedded=type" json:"type"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Dirent) Reset()         { *m = Dirent{} }
func (m *Dirent) String() string { return proto.CompactTextString(m) }
func (*Dirent) ProtoMessage()    {}

func (m *Dirent) GetInode() uint64 {
	if m != nil {
		return m.Inode
	}
	return 0
}

type Type struct {
	File             *File  `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Dir              *Dir   `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}

func (m *Type) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Type) GetDir() *Dir {
	if m != nil {
		return m.Dir
	}
	return nil
}

type File struct {
	Manifest         bazil_cas.Manifest `protobuf:"bytes,1,req,name=manifest" json:"manifest"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}

func (m *File) GetManifest() bazil_cas.Manifest {
	if m != nil {
		return m.Manifest
	}
	return bazil_cas.Manifest{}
}

// Dir is a directory stored fully in the database, not persisted
// in objects.
type Dir struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Dir) Reset()         { *m = Dir{} }
func (m *Dir) String() string { return proto.CompactTextString(m) }
func (*Dir) ProtoMessage()    {}

func init() {
}
func (this *Type) GetValue() interface{} {
	if this.File != nil {
		return this.File
	}
	if this.Dir != nil {
		return this.Dir
	}
	return nil
}

func (this *Type) SetValue(value interface{}) bool {
	switch vt := value.(type) {
	case *File:
		this.File = vt
	case *Dir:
		this.Dir = vt
	default:
		return false
	}
	return true
}
