// Code generated by protoc-gen-go.
// source: bazil.org/bazil/fs/wire/snap.proto
// DO NOT EDIT!

package wire

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// Snapshot as it is stored into database.
type SnapshotRef struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *SnapshotRef) Reset()         { *m = SnapshotRef{} }
func (m *SnapshotRef) String() string { return proto.CompactTextString(m) }
func (*SnapshotRef) ProtoMessage()    {}

func init() {
}
