// Code generated by protoc-gen-gogo.
// source: bazil.org/bazil/fs/wire/volume.proto
// DO NOT EDIT!

package wire

import proto "github.com/gogo/protobuf/proto"
import math "math"

// discarding unused import gogoproto "github.com/gogo/protobuf/gogoproto/gogo.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type KV struct {
	Local            *KV_Local      `protobuf:"bytes,1,opt,name=local" json:"local,omitempty"`
	External         []*KV_External `protobuf:"bytes,2,rep,name=external" json:"external,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}

func (m *KV) GetLocal() *KV_Local {
	if m != nil {
		return m.Local
	}
	return nil
}

func (m *KV) GetExternal() []*KV_External {
	if m != nil {
		return m.External
	}
	return nil
}

type KV_Local struct {
	// Must be exactly 32 bytes long.
	Secret           []byte `protobuf:"bytes,1,opt,name=secret" json:"secret"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *KV_Local) Reset()         { *m = KV_Local{} }
func (m *KV_Local) String() string { return proto.CompactTextString(m) }
func (*KV_Local) ProtoMessage()    {}

func (m *KV_Local) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

type KV_External struct {
	Path string `protobuf:"bytes,1,req,name=path" json:"path"`
	// Must be exactly 32 bytes long.
	Secret           []byte `protobuf:"bytes,2,opt,name=secret" json:"secret"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *KV_External) Reset()         { *m = KV_External{} }
func (m *KV_External) String() string { return proto.CompactTextString(m) }
func (*KV_External) ProtoMessage()    {}

func (m *KV_External) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *KV_External) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

type VolumeConfig struct {
	// Must be exactly 64 bytes long.
	VolumeID         []byte `protobuf:"bytes,1,req,name=volumeID" json:"volumeID"`
	Storage          KV     `protobuf:"bytes,2,req,name=storage" json:"storage"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *VolumeConfig) Reset()         { *m = VolumeConfig{} }
func (m *VolumeConfig) String() string { return proto.CompactTextString(m) }
func (*VolumeConfig) ProtoMessage()    {}

func (m *VolumeConfig) GetVolumeID() []byte {
	if m != nil {
		return m.VolumeID
	}
	return nil
}

func (m *VolumeConfig) GetStorage() KV {
	if m != nil {
		return m.Storage
	}
	return KV{}
}

func init() {
}
