// Code generated by protoc-gen-go.
// source: bazil.org/bazil/fs/wire/volume.proto
// DO NOT EDIT!

package wire

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type VolumeStorage struct {
	Name           string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Backend        string `protobuf:"bytes,2,opt,name=backend" json:"backend,omitempty"`
	SharingKeyName string `protobuf:"bytes,3,opt,name=sharingKeyName" json:"sharingKeyName,omitempty"`
}

func (m *VolumeStorage) Reset()         { *m = VolumeStorage{} }
func (m *VolumeStorage) String() string { return proto.CompactTextString(m) }
func (*VolumeStorage) ProtoMessage()    {}

type VolumeConfig struct {
	// Must be exactly 64 bytes long.
	VolumeID []byte           `protobuf:"bytes,1,opt,name=volumeID,proto3" json:"volumeID,omitempty"`
	Storage  []*VolumeStorage `protobuf:"bytes,2,rep,name=storage" json:"storage,omitempty"`
}

func (m *VolumeConfig) Reset()         { *m = VolumeConfig{} }
func (m *VolumeConfig) String() string { return proto.CompactTextString(m) }
func (*VolumeConfig) ProtoMessage()    {}

func (m *VolumeConfig) GetStorage() []*VolumeStorage {
	if m != nil {
		return m.Storage
	}
	return nil
}

func init() {
}
