// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bazil.org/bazil/cas/wire/manifest.proto

package wire

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Manifest struct {
	Root                 []byte   `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ChunkSize            uint32   `protobuf:"varint,3,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	Fanout               uint32   `protobuf:"varint,4,opt,name=fanout,proto3" json:"fanout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Manifest) Reset()         { *m = Manifest{} }
func (m *Manifest) String() string { return proto.CompactTextString(m) }
func (*Manifest) ProtoMessage()    {}
func (*Manifest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f5b64bcf9243672, []int{0}
}

func (m *Manifest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Manifest.Unmarshal(m, b)
}
func (m *Manifest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Manifest.Marshal(b, m, deterministic)
}
func (m *Manifest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manifest.Merge(m, src)
}
func (m *Manifest) XXX_Size() int {
	return xxx_messageInfo_Manifest.Size(m)
}
func (m *Manifest) XXX_DiscardUnknown() {
	xxx_messageInfo_Manifest.DiscardUnknown(m)
}

var xxx_messageInfo_Manifest proto.InternalMessageInfo

func (m *Manifest) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *Manifest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Manifest) GetChunkSize() uint32 {
	if m != nil {
		return m.ChunkSize
	}
	return 0
}

func (m *Manifest) GetFanout() uint32 {
	if m != nil {
		return m.Fanout
	}
	return 0
}

func init() {
	proto.RegisterType((*Manifest)(nil), "bazil.cas.Manifest")
}

func init() {
	proto.RegisterFile("bazil.org/bazil/cas/wire/manifest.proto", fileDescriptor_8f5b64bcf9243672)
}

var fileDescriptor_8f5b64bcf9243672 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0x4a, 0xac, 0xca,
	0xcc, 0xd1, 0xcb, 0x2f, 0x4a, 0xd7, 0x07, 0xb3, 0xf4, 0x93, 0x13, 0x8b, 0xf5, 0xcb, 0x33, 0x8b,
	0x52, 0xf5, 0x73, 0x13, 0xf3, 0x32, 0xd3, 0x52, 0x8b, 0x4b, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2,
	0x85, 0x38, 0x21, 0x0a, 0x93, 0x13, 0x8b, 0x95, 0x32, 0xb8, 0x38, 0x7c, 0xa1, 0x92, 0x42, 0x42,
	0x5c, 0x2c, 0x45, 0xf9, 0xf9, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0x36, 0x48,
	0xac, 0x38, 0xb3, 0x2a, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x25, 0x08, 0xcc, 0x16, 0x92, 0xe1,
	0xe2, 0x4c, 0xce, 0x28, 0xcd, 0xcb, 0x0e, 0x06, 0x49, 0x30, 0x2b, 0x30, 0x6a, 0xf0, 0x06, 0x21,
	0x04, 0x84, 0xc4, 0xb8, 0xd8, 0xd2, 0x12, 0xf3, 0xf2, 0x4b, 0x4b, 0x24, 0x58, 0xc0, 0x52, 0x50,
	0x9e, 0x13, 0x5b, 0x14, 0x0b, 0xc8, 0x2d, 0x49, 0x6c, 0x60, 0x37, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x84, 0xb1, 0x75, 0x44, 0xae, 0x00, 0x00, 0x00,
}
