// Code generated by protoc-gen-go.
// source: bazil.org/bazil/cas/wire/manifest.proto
// DO NOT EDIT!

/*
Package wire is a generated protocol buffer package.

It is generated from these files:
	bazil.org/bazil/cas/wire/manifest.proto

It has these top-level messages:
	Manifest
*/
package wire

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Manifest struct {
	Root      []byte `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Size      uint64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	ChunkSize uint32 `protobuf:"varint,3,opt,name=chunkSize" json:"chunkSize,omitempty"`
	Fanout    uint32 `protobuf:"varint,4,opt,name=fanout" json:"fanout,omitempty"`
}

func (m *Manifest) Reset()         { *m = Manifest{} }
func (m *Manifest) String() string { return proto.CompactTextString(m) }
func (*Manifest) ProtoMessage()    {}
